// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Comment struct {
	ID       string     `json:"id"`
	Post     *Post      `json:"post"`
	Parent   *Comment   `json:"parent,omitempty"`
	Author   string     `json:"author"`
	Text     string     `json:"text"`
	CreateAt time.Time  `json:"createAt"`
	Children []*Comment `json:"children"`
}

type CommentsPage struct {
	Comments   []*Comment `json:"comments"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID               string        `json:"id"`
	Title            string        `json:"title"`
	Content          string        `json:"content"`
	Author           string        `json:"author"`
	CommentsDisabled bool          `json:"commentsDisabled"`
	Comments         *CommentsPage `json:"comments"`
	CreateAt         time.Time     `json:"createAt"`
	UpdateAt         time.Time     `json:"updateAt"`
}

type Query struct {
}

type Subscription struct {
}
